version: "3.9"

networks:
  dev:

services:
  backend:
    build:
      context: ./server
    ports:
      - "3001:3000"
    networks:
      - dev

  frontend:
    build:
      context: ./client
    ports:
      - "3002:80"
    networks:
      - dev